---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.20.0
  name: plmns.
spec:
  group: ""
  names:
    kind: PLMN
    listKind: PLMNList
    plural: plmns
    singular: plmn
  scope: Namespaced
  versions:
  - name: ""
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PLMNSpec defines the characteristics of a deployment of a
              network function
            properties:
              PLMNInfo:
                description: PLMNInfo defines the list of PLMN to configure for core
                  NFs
                items:
                  description: PLMNInfo defines the structure of PLMN
                  properties:
                    nssai:
                      description: NSSAI defines the Network Slice Selection Assistance
                        Information
                      items:
                        description: NSSAI defines the Network Slice Selection Assistance
                          Information
                        properties:
                          sd:
                            description: Sd defines Service Differentiator
                            pattern: ^[A-Fa-f0-9]{6}$
                            type: string
                          sst:
                            description: Sst defines Slice/Service Type
                            maximum: 255
                            minimum: 0
                            type: integer
                        required:
                        - sst
                        type: object
                      type: array
                    plmnID:
                      description: PLMNID defines the PLMN Identifier
                      properties:
                        mcc:
                          description: mcc defines the mobile country code
                          pattern: '[02-79][0-9][0-9]'
                          type: string
                        mnc:
                          description: mnc defines the mobile network code
                          pattern: '[0-9][0-9][0-9]|[0-9][0-9]'
                          type: string
                      required:
                      - mcc
                      - mnc
                      type: object
                    tac:
                      description: tac defines the tracking area code
                      format: int32
                      maximum: 16777215
                      minimum: 0
                      type: integer
                  required:
                  - nssai
                  - plmnID
                  - tac
                  type: object
                type: array
            required:
            - PLMNInfo
            type: object
          status:
            description: PLMNStatus defines the observed state of PLMN
            type: object
        type: object
    served: true
    storage: true
